---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cns-kube
  namespace: default
  labels:
    name: cns-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cns-kube
  template:
    metadata:
      labels:
        app: "cns-kube"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-port: "3001"
        dapr.io/app-id: "cns-kube"
        dapr.io/log-level: "debug"
    spec:
      serviceAccountName: cns-kube
      containers:
        - name: cns-kube
          image: us-central1-docker.pkg.dev/padi-staging/public/cns-kube:eab198c
          ports:
          - containerPort: 3001
          env:
          - name: CNS_CONTEXT
            value: "9PJHsewx59TfULsafF77"
          - name: HELM_BINARY_PATH
            value: "/usr/local/bin/helm"
          - name: DEBUG
            value: "true"
