apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cns-kube
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cns-kube
subjects:
- kind: ServiceAccount
  name: cns-kube
  namespace: default
